-- MySQL Script generated by MySQL Workbench
-- Sat May 11 21:04:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema imdb_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `imdb_db` ;

-- -----------------------------------------------------
-- Schema imdb_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imdb_db` DEFAULT CHARACTER SET utf8 ;
USE `imdb_db` ;

-- -----------------------------------------------------
-- Table `imdb_db`.`ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdb_db`.`ratings` ;

CREATE TABLE IF NOT EXISTS `imdb_db`.`ratings` (
  `tconst` VARCHAR(45) NOT NULL,
  `average_rating` FLOAT NULL,
  `number_of_votes` INT NULL,
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdb_db`.`title_basics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdb_db`.`title_basics` ;

CREATE TABLE IF NOT EXISTS `imdb_db`.`title_basics` (
  `tconst` VARCHAR(45) NOT NULL,
  `primary_title` VARCHAR(255) NULL,
  `start_year` INT NULL,
  `runtime` INT NULL,
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdb_db`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdb_db`.`genres` ;

CREATE TABLE IF NOT EXISTS `imdb_db`.`genres` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(45) NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdb_db`.`title_has_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdb_db`.`title_has_genres` ;

CREATE TABLE IF NOT EXISTS `imdb_db`.`title_has_genres` (
  `tconst` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`tconst`, `genre_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
